
language: python
python:
  - "3.6"
  - "3.7"
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py36
before_install:
  - pip install codecov
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install tox tox-travis
script:
  - tox
after_success:
  - codecov

